In [1]:
import numpy as np
import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors
import helpers_global
import cv2

In [7]:
start =(0,0)
goal = (34,49)

data = np.zeros((35, 50))

occupancy_grid = data.copy()
#occupancy_grid[0:25, 6]=1
#occupancy_grid[33:35, 12:30]=1
#occupancy_grid[10:33, 12]=1






path = helpers_global.global_final(occupancy_grid, start, goal, "8N")



In [3]:
array_with_origin_bottom_left = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Inverser l'origine avec OpenCV
array_with_origin_top_left = cv2.flip(array_with_origin_bottom_left, 0)

# Afficher les résultats
print("Array avec origine en bas à gauche :\n", array_with_origin_bottom_left)
print("\nArray avec origine en haut à gauche :\n", array_with_origin_top_left)

Array avec origine en bas à gauche :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array avec origine en haut à gauche :
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [20]:
path

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 29, 29, 30, 30, 31,
        31, 32, 32, 33, 33, 33, 34],
       [ 0,  1,  2,  3,  4,  5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
        43, 44, 45, 46, 47, 48, 49]])